#ifndef EAT_ANIMATION_H

#define EAT_ANIMATION_H

// Animazioni dei giocatori...

#define GIOCATORE_FERMO 0
#define GIOCATORE_RESPIRA 1
#define GIOCATORE_RESPIRA_PALLA 2
#define GIOCATORE_CORSA_LENTA 3
#define GIOCATORE_CORSA_MEDIA 4
#define GIOCATORE_CORSA_VELOCE 5
#define GIOCATORE_CORSA_LENTA_PALLA 6
#define GIOCATORE_CORSA_MEDIA_PALLA 7
#define GIOCATORE_CORSA_VELOCE_PALLA 8
#define GIOCATORE_CAMBIO_ORARIO 9
#define GIOCATORE_CAMBIO_ANTI 10
#define GIOCATORE_SCIVOLATA 11
#define GIOCATORE_ALZATI 12
#define GIOCATORE_TESTA_AVANTI 13
#define GIOCATORE_TESTA_SINISTRA 14
#define GIOCATORE_TESTA_DESTRA 15
#define GIOCATORE_RIMESSA 16
#define GIOCATORE_TACCO 17
#define GIOCATORE_TIRO 18
#define GIOCATORE_STOP_PIEDE 19
#define GIOCATORE_STOP_PETTO 20
#define GIOCATORE_CADUTA 21
#define GIOCATORE_TUFFO_TESTA 22
#define GIOCATORE_INVERSIONE_MARCIA_PALLA 23
#define GIOCATORE_CONTRASTO 24
#define GIOCATORE_DOPORIMESSA 25
#define GIOCATORE_PREPARA_RIMESSA 26
#define GIOCATORE_RECUPERA_PALLA 27
#define GIOCATORE_CORSA_PARZIALE 28
#define GIOCATORE_RIALZA_AVANTI 29
#define GIOCATORE_BATTUTA    30
#define GIOCATORE_INVERSIONE_MARCIA 31
#define GIOCATORE_CADUTA_FERMO 32
#define GIOCATORE_PASSAGGIO 33
#define GIOCATORE_STACCO  34
#define GIOCATORE_ATTERRA 35
#define GIOCATORE_ESPULSO 36
#define GIOCATORE_ROVESCIATA 37
#define GIOCATORE_ASPETTA 38
#define GIOCATORE_NONPOSSO 39
#define GIOCATORE_GIRATA_SINISTRA 40
#define GIOCATORE_GIRATA_DESTRA 41
#define GIOCATORE_PREGIRATA 42
#define GIOCATORE_PRETUFFO 43
#define GIOCATORE_CADUTA_CARPONI 44
#define GIOCATORE_RIALZA_CARPONI 45
#define GIOCATORE_INFORTUNIO 46
#define GIOCATORE_PRIMA_ESULTANZA 47
#define GIOCATORE_ULTIMA_ESULTANZA 53
#define GIOCATORE_DISPERAZIONE_EST 54
#define GIOCATORE_DISPERAZIONE_OVEST 55

#define ARBITRO_FERMO 0
#define ARBITRO_CORSA 1
#define ARBITRO_FISCHIA 2
#define ARBITRO_FALLO 3
#define ARBITRO_CARTELLINO 4

#define GL_FERMO 0
#define GL_CORSA 1
#define GL_INVERSIONE 2
#define GL_FALLO 3
#define GL_FUORI_1 4
#define GL_FUORI_0 5

#define PORTIERE_FERMO    0
#define PORTIERE_FERMO_PALLA 1
#define PORTIERE_CORSA    2
#define PORTIERE_ATTENTO 3
#define PORTIERE_RINVIO_PIEDE_EST    4
#define PORTIERE_RINVIO_PIEDE_OVEST    5
#define PORTIERE_RINVIO_MANO_PRIMA_EST    6
#define PORTIERE_RINVIO_MANO_DOPO_EST    7
#define PORTIERE_RINVIO_MANO_PRIMA_OVEST    8
#define PORTIERE_RINVIO_MANO_DOPO_OVEST        9
#define PORTIERE_RINVIO_LIBERO_PRIMA_EST    10
#define PORTIERE_RINVIO_LIBERO_PRIMA_OVEST    11
#define PORTIERE_RACCOGLI_PALLA            12
#define PORTIERE_TUFFO_USCITA_PRENDI        13
#define PORTIERE_TUFFO_USCITA_MANCA        14
#define PORTIERE_SALTO_PRENDI            15
#define PORTIERE_SALTO_MANCA            16
#define PORTIERE_PRENDI_MEZZARIA        17
#define PORTIERE_TUFFO_DX_ALTO        18
#define PORTIERE_TUFFO_SX_ALTO        19
#define PORTIERE_TUFFO_DX_ALTO_PRENDI    20
#define PORTIERE_TUFFO_SX_ALTO_PRENDI    21
#define PORTIERE_TUFFO_DX_ALTO_MANCA    22
#define PORTIERE_TUFFO_SX_ALTO_MANCA    23
#define PORTIERE_TUFFO_DX_BASSO_MANCA    24
#define PORTIERE_TUFFO_SX_BASSO_MANCA    25
#define PORTIERE_TUFFO_DX_BASSO_PRENDI    26
#define PORTIERE_TUFFO_SX_BASSO_PRENDI    27
#define PORTIERE_TUFFO_DX_BASSO        28
#define PORTIERE_TUFFO_SX_BASSO        29
#define PORTIERE_TERRA_PALLA            30
#define PORTIERE_TERRA                31
#define PORTIERE_CAMMINA_LATERALE    32
#define PORTIERE_PRERIGORE        33
#endif
