#define SOUND_BASE 32

#define VEDIAMO_L_AZIONE_AL_REPLAY        0+SOUND_BASE
#define ECCO_IL_REPLAY                1+SOUND_BASE

#define LE_SQUADRE_STANNO_ENTRANDO_IN_CAMPO    2+SOUND_BASE
#define IL_TERRENO_E_IN_OTTIME_CONDIZIONI    3+SOUND_BASE
#define IL_TERRENO_E_IN_PESSIME_CONDIZIONI    4+SOUND_BASE
#define IL_CAMPO_E_COPERTO_DALLA_NEVE        5+SOUND_BASE
#define GLI_SPALTI_SONO_ESAURITI_IN_OGNI_ORDINE_DI_POSTI    6+SOUND_BASE
#define SARA_SICURAMENTE_UNA_PARTITA_MOLTO_INTERESSANTE    7+SOUND_BASE
#define LE_SQUADRE_SONO_SCHIERATE        8+SOUND_BASE

#define PERDE_IL_PALLONE            9+SOUND_BASE
#define PERDE_LA_PALLA                10+SOUND_BASE
#define PORTA_AVANTI_IL_PALLONE            11+SOUND_BASE
#define AVANZA_PALLA_AL_PIEDE            12+SOUND_BASE
#define PORTA_AVANTI_LA_PALLA            13+SOUND_BASE
#define HA_LA_POSSIBILITA_DI_TIRARE        14+SOUND_BASE

#define TIRA                    15+SOUND_BASE
#define    TIRO                    16+SOUND_BASE
#define PROVA_IL_TIRO                17+SOUND_BASE
#define PROVA_LA_BOTTA                18+SOUND_BASE
#define PALLA_PERSA                19+SOUND_BASE

#define USCITA_DEL_PORTIERE            20+SOUND_BASE
#define USCITA_SICURA_DEL_PORTIERE        21+SOUND_BASE
#define IL_PORTIERE_BLOCCA_IL_PALLONE        22+SOUND_BASE
#define IL_PORTIERE_SI_IMPOSSESSA_DEL_PALLONE    23+SOUND_BASE
#define IL_PORTIERE_PARA_SENZA_DIFFICOLTA    24+SOUND_BASE
#define GRAN_PARATA_DEL_PORTIERE        25+SOUND_BASE
#define PARATA_DEL_PORTIERE            26+SOUND_BASE
#define IL_PORTIERE_PARA            27+SOUND_BASE
#define IL_PORTIERE_SI_DISTENDE_IN_TUFFO    28+SOUND_BASE
#define IL_PORTIERE_NON_TRATTIENE_IL_PALLONE    29+SOUND_BASE
#define IL_PORTIERE_RESPINGE            30+SOUND_BASE
#define RINVIO_DA_FONDO_CAMPO            31+SOUND_BASE
#define IL_PORTIERE_SI_APPRESTA_A_RINVIARE    32+SOUND_BASE

#define ED_E_GOL                33+SOUND_BASE
#define GOOOOOOOOL                34+SOUND_BASE
#define GOL                    35+SOUND_BASE
#define RETE                    36+SOUND_BASE
#define PALLA_IN_RETE                37+SOUND_BASE

#define PALOOO                    38+SOUND_BASE
#define LA_PALLA_COLPISCE_IL_PALO        39+SOUND_BASE
#define TRAVERSA                40+SOUND_BASE
#define PALLA_SULLA_TRAVERSA            41+SOUND_BASE

#define RIMESSA_LATERALE            42+SOUND_BASE
#define CALCIO_D_ANGOLO                43+SOUND_BASE
#define CALCIO_DI_PUNIZIONE            44+SOUND_BASE
#define FALLO                    45+SOUND_BASE
#define CALCIO_DI_RIGORE            46+SOUND_BASE
#define CALCIO_D_INIZIO                47+SOUND_BASE
#define L_ARBITRO_ESTRAE_IL_CARTELLINO_GIALLO    48+SOUND_BASE
#define L_ARBITRO_ESTRAE_IL_CARTELLINO_ROSSO    49+SOUND_BASE
#define PALLA_FUORI                50+SOUND_BASE

#define PALLA_A_CENTROCAMPO            51+SOUND_BASE
#define SI_LOTTA_A_CENTROCAMPO            52+SOUND_BASE
#define IL_GIOCO_RISTAGNA_A_CENTROCAMPO        53+SOUND_BASE
#define LA_PARTITA_E_MOLTO_EQUILIBRATA        54+SOUND_BASE

#define STA_DOMINANDO_LA_PARTITA        55+SOUND_BASE
#define E_IN_BALIA_DELL_AVVERSARIO        56+SOUND_BASE
#define MANTIENE_IL_POSSESSO_DEL_PALLONE    57+SOUND_BASE
#define CI_PROVA_SULLA_FASCIA            58+SOUND_BASE
#define AVANZA_SULLA_FASCIA_LATERALE        59+SOUND_BASE

#define PASSAGGIO_IN_PROFONDITA            60+SOUND_BASE
#define LANCIO_IN_PROFONDITA            61+SOUND_BASE
#define TENTATIVO_DI_LANCIO_IN_PROFONDITA    62+SOUND_BASE

#define E_UN_ASSEDIO                63+SOUND_BASE
#define SI_GIOCA_AD_UNA_PORTA            64+SOUND_BASE

#define IL_TEMPO_STA_PER_FINIRE            65+SOUND_BASE
#define QUESTA_SARA_PROBABILMENTE_L_ULTIMA_AZIONE 66+SOUND_BASE
#define FINE_PRIMO_TEMPO            67+SOUND_BASE
#define IL_PRIMO_TEMPO_E_TERMINATO        68+SOUND_BASE
#define FINE_SECONDO_TEMPO            69+SOUND_BASE
#define SONO_INIZIATI_I_TEMPI_SUPPLEMENTARI    70+SOUND_BASE
#define SECONDO_TEMPO_SUPPLEMENTARE        71+SOUND_BASE
#define SECONDO_TEMPO                72+SOUND_BASE
#define INIZIA_LA_PARTITA            73+SOUND_BASE
